name: Build and Test
on: [push, pull_request]
jobs:
  build:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    uses: ./.github/workflows/base-build-and-test.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
